- name: Deploy Apache Webserver
  hosts: all
  become: yes
  tasks:
   - name: Install apache2
     apt:
      update_cache: yes
      name: apache2
      state: present
   - name: start and enable service of apache2
     service:
       name: apache2
       state: started
       enabled: yes

